format = """
$username\
$hostname \
$directory \
$git_branch \
$python \
$character
"""
add_newline = false

[username]
format = "[${user}@](bold green)"
show_always = true

[hostname]
format = "[$hostname](bold green)"
ssh_only = false

[directory]
format = "[ğŸ–¿ $path](bold 32)"  # Apenas o nome da pasta atual
truncation_length = 2                 # Garante que sÃ³ o Ãºltimo diretÃ³rio apareÃ§a
home_symbol = "~"                      # Mostra "~" quando estiver no home
read_only = " ğŸ”’"

[git_branch]
format = "[ğŸŒ¿$branch](bold purple)"
symbol = ""

[python]
format = "via[Python $version](bold magenta) "
symbol = ""

[character]
format = "$symbol "
success_symbol = "[â¯](bold blue)"
error_symbol = "[â¯](bold red)"

